### ISSUE TITLE
Not Displaying Add to HomeScreen Popup in Mobile Devices

### ISSUE THREAD

**Issue by prema1432** [nimaes80/django-simple-pwa#3]
Hi Team,
Not Displaying Add to HomeScreen Popup in Mobile Devices.

how can we add that option? pls help me @nimaes80

**Comment by nimaes80** [comment]
Hello @prema1432,

If you do every thing correctly (as mentioned in [docs](https://django-simple-pwa.readthedocs.io/fa/latest/)), you can see install button on top of browser screen or in some of other ones you can install it by [this](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#how_do_you_use_it) way.
If you need some other verification you should add these JavaScript code to your [static files](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#javascript_for_handling_the_install)


Also note that PWA only install on devices when server runs on **HTTPS** protocol or localhost that means **you cant install PWA when you run it on NAT** for example `192.168.1.2` IP address only can install PWA when runs on HTTPS

**Comment by prema1432** [comment]
Thanks, @nimaes80 it's working.

how can we add the splash screen image?

**Comment by nimaes80** [comment]
As I mentioned in [documents](https://django-simple-pwa.readthedocs.io/fa/latest/customization.html#id4), You can find out everything you need in PWA documents; However for changing splash screen color or using icons for other [purpose](https://web.dev/add-manifest/#icons) you should add `purpose` to `icons` list for example :
```
PWA_CONFIG = {
        ...,
        "theme_color": "#7820f5", # <--- hex color
        "background_color": "#7820f5", # <--- hex color
        "icons": [
                {
                        "src": "/static/pwa/icons/72x72.png",
                        "type": "image/png",
                        "sizes": "72x72",
                        "purpose": "maskable", # <--- purpose
                },
         ],
        ...,
}
```

All of these dosnt related to `django-simple-pwa` you need read more about PWA `manifest.json`.

Thanks.

**Comment by prema1432** [comment]
@nimaes80 thank you... it's working fine.
